#theme = 'hugo-theme-learn'
theme = 'risotto'
baseUrl = 'https://rumca-js.github.io/quickstart/public'
title = "My name is rumca-js"
languageCode = 'en-us'

paginate = 30

[params]
   author="rumca-js"
   description="This is my site"
   # for SEO
   keywords = ["Programming", "Blog"]

[[params.social]]
   title = "github"
   url="https://github.com/rumca-js"

[menu]
   [[menu.main]]
    name="Home"
    url="/"
    weight=1
   [[menu.main]]
    name="Blog"
    url="/posts"
    weight=2

