theme = 'risotto'
baseUrl = 'https://rumca-js.github.io/quickstart/public'
title = "rumca-js"
languageCode = 'en-us'

paginate = 30

[params]
   author="rumca-js"
   description="This is my site"
   # for SEO
   keywords = ["Programming", "Blog"]

# sidebar
[params.about]
title="rumca-js"
description = "...[]..."

[menu]
   [[menu.main]]
    name="Blog"
    url="/posts"
    weight=1
   [[menu.main]]
    name="Main"
    url="https://rumca-js.github.io"
    weight=2
   [[menu.lists]]
    name="Main"
    url="https://rumca-js.github.io/quickstart/public/static_lists"
    weight=3

[[params.socialLinks]]
   icon = "fa-brands fa-github"
   title = "github"
   url = "https://github.com/rumca-js"

[[params.socialLinks]]
   icon = "fa-brands fa-docker"
   title = "docker"
   url = "https://hub.docker.com/r/rozbujnik/django-link-archive"

[[params.socialLinks]]
   icon = "fa-brands fa-reddit"
   title = "reddit"
   url = "https://www.reddit.com/user/renegat0x0"

[[params.socialLinks]]
   icon = "fa-brands fa-youtube"
   title = "YouTube"
   url = "https://www.youtube.com/channel/UCilzRuEs5uBWp06PWw1ejkA"

[[params.socialLinks]]
   icon = "fa-brands fa-paint-brush"
   title = "DeviantArt"
   url = "https://www.deviantart.com/renegat0x0"
