#theme = 'hugo-theme-learn'
theme = 'risotto'
baseUrl = 'https://rumca-js.github.io/quickstart/public'
title = "My name is rumca-js"
languageCode = 'en-us'

paginate = 30

[params]
   author="rumca-js"
   description="This is my site"
   # for SEO
   keywords = ["Programming", "Blog"]

# sidebar
[params.about]
title="rumca-js"
description = "...[]..."

[menu]
   [[menu.main]]
    name="Main"
    url="https://rumca-js.github.io"
    weight=1
   [[menu.main]]
    name="Blog"
    url="/posts"
    weight=2

[[params.socialLinks]]
   title = "github"
   url="https://github.com/rumca-js"

